server:
  #端口号
  port: 8088

# datasource
spring:
  datasource:
#    url: jdbc:mysql://103.10.87.19:3306/testxngc?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://82.157.236.93:3306/mydb?useUnicode=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123Mxl456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 200
      min-idle: 100
      max-total: 500
  redis:
    host: 103.10.87.19
    port: 6379
    password: sa1234!@#$


# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml # mapper映射文件路径
  type-aliases-package: com.gttss.entity

  # config-location:  # 指定mybatis的核心配置文件

  # 打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启为空时也set数据
    call-setters-on-nulls: true
