src: classpath:ftl
spring:
  datasource:
    url: jdbc:mysql://39.105.196.139:3306/test_temp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: spss123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

