src: classpath:ftl
spring:
  datasource:
    url: jdbc:mysql://103.10.87.19:3306/testxngc?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sa1234!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

